version: "2.2"

services:
  postgres:
    image: postgres:10.7-alpine
    restart: always
    volumes: 
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
      - interviewme_db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: hh
      POSTGRES_PASSWORD: hh-password
      POSTGRES_DB: interviewme
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hh -d interviewme"]
      interval: 10s
      timeout: 5s
      retries: 5
  backend:
    build: ./backend
    depends_on: 
      postgres:
        condition: service_healthy
  frontend:
    build: ./frontend
    ports: 
      - "8081:80"
    depends_on: 
      - backend

volumes: 
  interviewme_db: